### ISSUE TITLE
Error when parsing operator symbols

### ISSUE THREAD

**Issue by Hirevo** [SOM-st/som-java#30]
While solving the [Advent of Code 2022 using SOM] today, I encountered an issue where som-java would not successfully parse the symbol `#-`, giving the following error:

[Advent of Code 2022 using SOM]: https://github.com/Hirevo/advent-of-code-2022

```
Error: ./ParseTest.som:4: unexpected symbol, expected: Identifier, but found: Minus
```

Since this is the only operator symbol that doesn't parse (among `#+`, `#*`, `#/` and `#%`), maybe it is because of the fact that the minus symbol can be used in integers, and since symbol names can't start with an integer, the parser probably rejects that code entirely.

Here is a minimal example that triggers the error:

```
ParseTest = (
  run: args = (
    #- println.
  )
)
```

Using `'-' asSymbol` instead makes the error go away and successfully yields the `#-` symbol.

**Comment by Hirevo** [comment]
I found that this error also happens within CSOM and jsSOM (the latter was tested from the [`som-st` web REPL]).  
These are the ones I had on hand to quickly test with, so maybe some others (like SOM++ or PySOM) are also affected.  

Should I submit a GitHub issue for each of the affected projects, or this single one suffices ?

[`som-st` web REPL]: https://som-st.github.io

**Comment by smarr** [comment]
Hm, thanks. Sounds indeed like a bug to me.
I am currently traveling, so will try to look into this once back.

Thanks!
Stefan

**Comment by smarr** [comment]
Fixed with https://github.com/SOM-st/SOM/pull/104
